"""init

Revision ID: 5b79460e27ed
Revises: f499b7199808
Create Date: 2026-03-11 17:00:02.956872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5b79460e27ed'
down_revision: Union[str, Sequence[str], None] = 'f499b7199808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_ibfk_5', 'users', type_='foreignkey')
    op.drop_constraint('users_ibfk_1', 'users', type_='foreignkey')
    op.drop_constraint('users_ibfk_4', 'users', type_='foreignkey')
    op.drop_constraint('users_ibfk_6', 'users', type_='foreignkey')
    op.drop_constraint('users_ibfk_3', 'users', type_='foreignkey')
    op.drop_constraint('users_ibfk_2', 'users', type_='foreignkey')
    op.drop_table('prefers')
    op.alter_column('chat_messages', 'image_path',
               existing_type=mysql.TEXT(),
               type_=sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'),
               existing_nullable=True)
    op.alter_column('chat_messages', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.drop_column('chat_messages', 'bookmark_yn')
    op.add_column('chat_rooms', sa.Column('history', sa.Text(), nullable=True))
    op.add_column('chat_rooms', sa.Column('adult_num', sa.Integer(), nullable=True))
    op.add_column('chat_rooms', sa.Column('child_num', sa.Integer(), nullable=True))
    op.add_column('chat_rooms', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('chat_rooms', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('chat_rooms', sa.Column('bookmark_yn', sa.Boolean(), nullable=False))
    op.alter_column('chat_rooms', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_chat_rooms_id'), 'chat_rooms', ['id'], unique=False)
    op.alter_column('country', 'code',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=10),
               comment='ISO Country Code',
               existing_nullable=False)
    op.alter_column('country', 'name',
               existing_type=mysql.VARCHAR(length=255),
               comment='Country Name',
               existing_nullable=True)
    op.add_column('users', sa.Column('profile_picture', sa.String(length=1000), nullable=True))
    op.add_column('users', sa.Column('plan_prefer', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('vibe_prefer', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('places_prefer', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('extra_prefer1', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('extra_prefer2', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('extra_prefer3', sa.String(length=255), nullable=True))
    op.alter_column('users', 'country_code',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=10),
               comment='ISO Country Code',
               existing_nullable=True)
    op.alter_column('users', 'is_join',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'is_prefer',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'celeb_prefer_id')
    op.drop_column('users', 'drama_prefer_id')
    op.drop_column('users', 'actor_prefer_id')
    op.drop_column('users', 'with_yn')
    op.drop_column('users', 'movie_prefer_id')
    op.drop_column('users', 'birthday')
    op.drop_column('users', 'vegan_yn')
    op.drop_column('users', 'dog_yn')
    op.drop_column('users', 'variety_prefer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('variety_prefer_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('dog_yn', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('vegan_yn', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('birthday', sa.DATE(), nullable=True))
    op.add_column('users', sa.Column('movie_prefer_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('with_yn', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('actor_prefer_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('drama_prefer_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('celeb_prefer_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_ibfk_2', 'users', 'prefers', ['movie_prefer_id'], ['id'])
    op.create_foreign_key('users_ibfk_3', 'users', 'prefers', ['drama_prefer_id'], ['id'])
    op.create_foreign_key('users_ibfk_6', 'users', 'country', ['country_code'], ['code'])
    op.create_foreign_key('users_ibfk_4', 'users', 'prefers', ['celeb_prefer_id'], ['id'])
    op.create_foreign_key('users_ibfk_1', 'users', 'prefers', ['actor_prefer_id'], ['id'])
    op.create_foreign_key('users_ibfk_5', 'users', 'prefers', ['variety_prefer_id'], ['id'])
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'is_prefer',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'is_join',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'country_code',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='ISO Country Code',
               existing_nullable=True)
    op.drop_column('users', 'extra_prefer3')
    op.drop_column('users', 'extra_prefer2')
    op.drop_column('users', 'extra_prefer1')
    op.drop_column('users', 'places_prefer')
    op.drop_column('users', 'vibe_prefer')
    op.drop_column('users', 'plan_prefer')
    op.drop_column('users', 'profile_picture')
    op.alter_column('country', 'name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='Country Name',
               existing_nullable=True)
    op.alter_column('country', 'code',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='ISO Country Code',
               existing_nullable=False)
    op.drop_index(op.f('ix_chat_rooms_id'), table_name='chat_rooms')
    op.alter_column('chat_rooms', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('chat_rooms', 'bookmark_yn')
    op.drop_column('chat_rooms', 'end_date')
    op.drop_column('chat_rooms', 'start_date')
    op.drop_column('chat_rooms', 'child_num')
    op.drop_column('chat_rooms', 'adult_num')
    op.drop_column('chat_rooms', 'history')
    op.add_column('chat_messages', sa.Column('bookmark_yn', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.alter_column('chat_messages', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('chat_messages', 'image_path',
               existing_type=sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.create_table('prefers',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('value', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('image_path', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
