"""add language

Revision ID: bef46e9cdb71
Revises: c7d8e9f0a1b2
Create Date: 2026-03-19 06:58:29.886570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bef46e9cdb71'
down_revision: Union[str, Sequence[str], None] = 'c7d8e9f0a1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('code', sa.String(length=10), nullable=False, comment='ISO Country Code'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='Country Name'),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_hot_places_id'), 'hot_places', ['id'], unique=False)
    op.alter_column('reservation_list', 'date',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
    op.create_index(op.f('ix_reservation_list_id'), 'reservation_list', ['id'], unique=False)
    op.add_column('users', sa.Column('language', sa.Enum('en', 'ko', 'ja', 'zh', name='languagetype'), nullable=False, comment='UI Language Preference'))
    op.alter_column('users', 'profile_picture',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('users', 'country_code',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=10),
               comment='ISO Country Code',
               existing_nullable=True)
    op.alter_column('users', 'is_join',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'is_prefer',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'is_prefer',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'is_join',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'country_code',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='ISO Country Code',
               existing_nullable=True)
    op.alter_column('users', 'profile_picture',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('users', 'language')
    op.drop_index(op.f('ix_reservation_list_id'), table_name='reservation_list')
    op.alter_column('reservation_list', 'date',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    op.drop_index(op.f('ix_hot_places_id'), table_name='hot_places')
    op.drop_table('country')
    # ### end Alembic commands ###
